server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.show_sql: true
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      javax.persistence.sharedCache.mode: NONE

springdoc:
  api-docs:
    enabled: false

app:
  about:
    path: fake/git.json
