springdoc:
  api-docs:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://85.198.109.181:5432/stp_prod_db
    username: 'prod_admin'
    password: '12345678'

app:
  about:
    path: git.json