springdoc:
  api-docs:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stp_db
    username: admin
    password: 12345678

  flyway.enabled: true
  flyway:
    url: jdbc:postgresql://127.0.0.1:5432/test
    locations: classpath:db/migration
    schemas: public
    user: admin
    password: 12345678
    baselineOnMigrate: true

app:
  about:
    path: git.json