CREATE TABLE note (
    id int8 NOT NULL,
    content TEXT NOT NULL,
    create_time TIMESTAMP NOT NULL
);

ALTER TABLE note ADD CONSTRAINT "pk_note" PRIMARY KEY (id);

CREATE SEQUENCE note_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 10
NO CYCLE;